apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pgpcloudbackup
  name: pgpcloudbackup-pvc
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
