apiVersion: batch/v1
kind: CronJob
metadata:
  name: pgpcloudbackup-cronjob
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pgpcloudbackup
            image: feridock/pgpcloudbackup:0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: PGPCB_CONFIG_FILE
              value: "/app/conf/.pcloud-config"
            - name: PGPCB_PUBLIC_PGP_KEY_FILE
              value: "/app/conf/encrypt-key.pub"
            - name: PGPCB_LOCAL_FOLDER
              value: "/input"
            - name: PGPCB_TEMP_FOLDER
              value: "/tmp"
            - name: PGPCB_REMOTE_FOLDER
              value: "/VSERVERBACKUP/mc-forge-1-12"
            volumeMounts:
            - mountPath: /input
              name: input
            - name: config
              mountPath: "/app/conf"
              readOnly: true
          volumes:
          - name: input
            persistentVolumeClaim:
              claimName: pgpcloudbackup-pvc
          - name: config
            secret:
              secretName: pgpcloudbackup-secret
          restartPolicy: Never
